# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  servers=[
    {
      :hostname => "Server1",
      :box => "ubuntu/focal64",
      :ip => "172.16.0.2",
      :ssh_port => '2200'
    },
    {
      :hostname => "Server2",
      :box => "ubuntu/focal64",
      :ip => "172.16.0.3",
      :ssh_port => '2201'
    },
    {
      :hostname => "Server3",
      :box => "ubuntu/focal64",
      :ip => "172.16.0.4",
      :ssh_port => '2202'
    }
  ]

  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = machine[:box]
      node.vm.hostname = machine[:hostname]
      node.vm.network :private_network, ip: machine[:ip]
      node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"

      node.vm.provision "file", source: "../../../consul/config/consulClientServerConfig.hcl", destination: "$HOME/temp/consulClientServerConfig.hcl"
      node.vm.provision "file", source: "../../../nomad/config/nomadClientServerConfig.hcl", destination: "$HOME/temp/nomadClientServerConfig.hcl"

      node.vm.provision "shell", path: "../init.sh", privileged: false

      node.vm.provision "shell" do |s|
        s.path = "../../../consul/execConsulClientServer.sh"
        s.args = machine[:ip]
        s.privileged = true
      end

      node.vm.provision "shell" do |s|
        s.path = "../../../nomad/execNomadClientServer.sh"
        s.args = machine[:ip]
        s.privileged = true
      end

      node.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", 2048]
        vb.customize ["modifyvm", :id, "--cpus", 2]
      end
    end
  end
end