# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  servers=[
    {
      :hostname => "Server1",
      :box => "ubuntu/focal64",
      :ip => "172.16.0.2",
      :ssh_port => '2200'
    },
    {
      :hostname => "Server2",
      :box => "ubuntu/focal64",
      :ip => "172.16.0.3",
      :ssh_port => '2201'
    },
    {
      :hostname => "Server3",
      :box => "ubuntu/focal64",
      :ip => "172.16.0.4",
      :ssh_port => '2202'
    },
    {
      :hostname => "Server4",
      :box => "ubuntu/focal64",
      :ip => "172.16.0.5",
      :ssh_port => '2203'
    }
  ]

  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = machine[:box]
      node.vm.hostname = machine[:hostname]
      node.vm.network :private_network, ip: machine[:ip]
      node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"

      config.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
        s.inline = <<-SHELL
          echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
          echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
        SHELL
      end

      node.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", 1024]
        vb.customize ["modifyvm", :id, "--cpus", 1]
      end
    end
  end
end