# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/focal64" # 20.04 LTS
  config.vm.hostname = "DevServer"
  config.vm.network :private_network, ip: "172.16.0.2"

  config.vm.provision "shell", path: "../init.sh", privileged: false

  config.vm.provision "file", source: "../../../consul/config/consulDevConfig.hcl", destination: "$HOME/etc/consul.d/consulDevConfig.hcl"
  config.vm.provision "file", source: "../../../nomad/config/nomadDevConfig.hcl", destination: "$HOME/temp/nomadDevConfig.hcl"
  config.vm.provision "file", source: "../../../vault/config/vaultDevConfig.hcl", destination: "$HOME/etc/vault.d/vaultDevConfig.hcl"

  config.vm.provision "shell" do |s|
    s.path = "../../../consul/execConsulDev.sh"
    s.privileged = true
  end

  config.vm.provision "shell" do |s|
    s.path = "../../../vault/execVaultDev.sh"
    s.privileged = true
  end

  config.vm.provision "shell" do |s|
    s.path = "../../../nomad/execNomadDev.sh"
    s.privileged = true
  end

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 4096]
    vb.customize ["modifyvm", :id, "--cpus", 2]
  end

end
