---

- include_tasks: ../../vaultTasks/createConfDir.yml

- include_tasks: ../../vaultTasks/createDataDir.yml

- include_tasks: ../../vaultTasks/createServiceConfDir.yml

- include_tasks: ../../vaultTasks/downloadVault.yml

- include_tasks: ../../vaultTasks/copyConfig.yml

- include_tasks: ../../vaultTasks/readRootKey.yml
  vars:
    - root_key_to_get: "{{ vault_transit_engine }}"

- name: Copy Service follower config file
  template:
    src: vaultFollowerConf.service.j2
    dest: "{{ vault_service_conf_dir }}/vaultEnv.conf"

- include_tasks: ../../vaultTasks/startVaultService.yml
  when: ansible_host == vault_seal_leader

- include_tasks: ../../vaultTasks/initOperatorAndWriteUnsealKeys.yml
  when: ansible_host == vault_seal_leader

- include_tasks: ../../vaultTasks/startVaultService.yml
  when: ansible_host != vault_seal_leader

- name: Wait vault startup
  pause:
    seconds: 10

- name: Join raft cluster
  shell: "vault operator raft join http://{{ vault_seal_leader }}:8200"
  environment:
    VAULT_ADDR: "http://{{ ansible_host }}:8200"
  when: ansible_host != vault_seal_leader
