---

- include_tasks: createDir.yml

- include_tasks: downloadVault.yml

- include_tasks: copyConfig.yml

- include_tasks: readRootKey.yml
  vars:
    - root_key_to_get: "{{ vault_transit_engine }}"

- name: Copy Service follower config file
  template:
    src: vaultFollowerConf.service.j2
    dest: "{{ vault_service_conf_dir }}/vaultEnv.conf"

- include_tasks: startVaultService.yml
  when: ansible_host == vault_seal_leader

- include_tasks: initOperatorAndWriteKeys.yml
  when: ansible_host == vault_seal_leader

- include_tasks: readKeysAndUnseal.yml
  when: ansible_host == vault_seal_leader

- include_tasks: startVaultService.yml
  when: ansible_host != vault_seal_leader

- name: Wait vault startup
  pause:
    seconds: 10

- name: Join raft cluster
  shell: "vault operator raft join http://{{ vault_seal_leader }}:8200"
  environment:
    VAULT_ADDR: "http://{{ ansible_host }}:8200"
  when: ansible_host != vault_seal_leader
