---
# tasks file for tools

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ubuntu_version }} stable"
    state: present

- name: Update apt and install docker-ce
  apt:
    update_cache: yes
    name: docker-ce
    state: latest

- name: Add docker group to user
  user:
    name: "{{ user }}"
    groups: docker
    append: yes

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Docker login
  docker_login:
    username: "{{ git_user }}"
    password: "{{ git_credential }}"
    registry: ghcr.io

- name: Pull default Docker image
  docker_image:
    name: ghcr.io/m0rgan01/park-trip/park-trip-api:master