

- name: Install server

  # les hosts concernés par ce playbook
  hosts: all
  # utilisateur pour les actions
  remote_user: root

  # les tâches
  tasks:

  # inclus les variables du fichiers
  - include_vars:
      file: vars.yml

  # Nom de la tache
  - name: User | Création de {{ user }}

    # Module
    user:
      name: "{{ user }}"
      shell: /bin/bash

  - name: User | Mise en place clef SSH
    authorized_key:
      user: "{{ user }}"
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  - name: APT | Update & Updagre
    apt:
      upgrade: dist
      update_cache: yes

  # la commande pour inclure un role
  - include_role:
      name: tools
  - include_role:
      name: docker