---

# les hosts concernés par ce playbook
- hosts: singleNode
  # utilisateur pour les actions
  remote_user: root

  vars:
    bootstrap_expect: 1
    retry_join: []

  vars_files:
    - ./vars.yml

  roles:
    - init
    - dockerInstall
    - consul
    - vaultSingleNode
    - nomad
    - observabilityJobs
