---

- hosts: vaultUnsealNode
  remote_user: root

  vars_files:
    - ./vars.yml

  roles:
    - init
    - vaultTransitEngine

- hosts: cluster
  remote_user: root

  vars:
    bootstrap_expect: 3
    retry_join: [ "172.16.0.2", "172.16.0.3", "172.16.0.4" ]

  vars_files:
    - ./vars.yml

  roles:
    - init
    - dockerInstall
    - consul
    - vaultCluster
    - nomad

