---

- name: Config file
  template:
    src: "{{ vault_config_file }}.hcl.j2"
    dest: "{{ vault_config_dir }}/{{ vault_config_file }}.hcl"

- name: Copy Service file
  template:
    src: vault.service.j2
    dest: /etc/systemd/system/vault.service