---

- name: Initialise Vault operator
  shell: vault operator init -recovery-shares=5 -recovery-threshold=3 -format json
  environment:
    VAULT_ADDR: "http://{{ ansible_host }}:8200"
  register: vault_init_results

- name: Parse output of vault init
  set_fact:
    vault_init_parsed: "{{ vault_init_results.stdout | from_json }}"

- name: Write unseal keys to files
  copy:
    dest: "{{ unseal_keys_dir_output }}/{{ inventory_hostname }}_recovery_key"
    content: "{{ vault_init_parsed.recovery_keys_hex | join('\n') }}"
  delegate_to: localhost

- name: Write root token to file
  copy:
    content: "{{ vault_init_parsed.root_token }}"
    dest: "{{ root_token_dir_output }}/{{ inventory_hostname }}_rootkey"
  delegate_to: localhost