# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  servers=[
    {
      :hostname => "Server1",
      :box => "ubuntu/focal64",
      :ip => "172.16.0.2",
      :ssh_port => '2200',
      :nomad_server => true,
      :consul_server => true
    },
    {
      :hostname => "Server2",
      :box => "ubuntu/focal64",
      :ip => "172.16.0.3",
      :ssh_port => '2201',
      :nomad_server => false,
      :consul_server => false
    },
    {
      :hostname => "Server3",
      :box => "ubuntu/focal64",
      :ip => "172.16.0.4",
      :ssh_port => '2202',
      :nomad_server => false,
      :consul_server => false
    },
    {
      :hostname => "Server4",
      :box => "ubuntu/focal64",
      :ip => "172.16.0.5",
      :ssh_port => '2203',
      :nomad_server => false,
      :consul_server => false
    }
  ]

  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = machine[:box]
      node.vm.hostname = machine[:hostname]
      node.vm.network :private_network, ip: machine[:ip]
      node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"

      node.vm.provision "file" do |s|
        s.source = machine[:consul_server] ? "../../consul/config/consulServerConfig.hcl" : "../../consul/config/consulClientConfig.hcl"
        s.destination = machine[:consul_server] ? "$HOME/temp/consulServerConfig.hcl" : "$HOME/temp/consulClientConfig.hcl"
      end

      node.vm.provision "file" do |s|
        s.source = machine[:nomad_server] ? "../../nomad/config/nomadServerConfig.hcl" : "../../nomad/config/nomadClientConfig.hcl"
        s.destination = machine[:nomad_server] ? "$HOME/temp/nomadServerConfig.hcl" : "$HOME/temp/nomadClientConfig.hcl"
      end

      node.vm.provision "shell", path: "../init.sh", privileged: false

      node.vm.provision "shell" do |s|
        s.path = machine[:nomad_server] ? "../../consul/execConsulServer.sh" : "../../consul/execConsulClient.sh"
        s.args = machine[:ip]
        s.privileged = true
      end

      node.vm.provision "shell" do |s|
        s.path = machine[:nomad_server] ? "../../nomad/execNomadServer.sh" : "../../nomad/execNomadClient.sh"
        s.args = machine[:ip]
        s.privileged = true
      end

      node.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", 1024]
        vb.customize ["modifyvm", :id, "--cpus", 2]
      end
    end
  end
end